version: "3"

services:
    redis:
      container_name: redis
      image: redis
      ports:
        - "6379:6379"
      restart: always
      command: redis-server --save 60 1 --loglevel warning
    backend:
      build: .
      container_name: blogbackend
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./core:/app
      ports: 
        - "8000:8000"
      environment:
        - SECRET_KEY=django-insecure-#!39atn!hu7kggiq&&1lfo1+hjhw!0=9_f0uuxv%0wsipzk@i0
        - DEBUG=True
      depends_on:
        - redis

    worker:
      build: .
      command: celery -A core worker --loglevel=info
      volumes:
        - ./core:/app
      depends_on:
        - redis
        - backend

    smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        - '5000:80'
        - '25:25'
        - '143:143'
      volumes:
          - smtp4dev-data:/smtp4dev
      environment:
        - ServerOptions__HostName=smtp4dev

    master:
      image: locustio/locust
      ports:
       - "8089:8089"
      volumes:
        - ./core/locust:/mnt/locust
      command: -f /mnt/locust/locustfile.py --master -H http://blogbackend:8000

    worker1:
      image: locustio/locust
      volumes:
        - ./core/locust:/mnt/locust
      command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  smtp4dev-data:





