# Generated by Django 3.2.23 on 2023-12-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231215_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unlike',
        ),
    ]
