# Generated by Django 3.2.23 on 2023-12-15 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_post_unlike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Dislike",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
