# Generated by Django 3.2.23 on 2023-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_auto_20231215_1934"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
