# Generated by Django 3.2.23 on 2023-12-19 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_comments_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ["created_date"]},
        ),
    ]
