# Generated by Django 3.2.23 on 2023-12-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_comments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comments",
            ),
        ),
    ]
